### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by tanayvaswani** [Adityaakr/Pay-Ease#5]
Some stuff is missing to setup the project, like .env.example, you can refer to [Pradhhumn Gautam's repo](https://github.com/pradhumngautam/paytm) for ref.

**Comment by Adityaakr** [comment]
Thank you for bringing that to my attention! I've included the `env.example` file now.

When working on this project solo, it's common for some aspects to be overlooked.

Please proceed with setting up the project and make any necessary adjustments as per your requirements.

Your feedback and insights are invaluable to me, so please follow each step carefully. If you encounter any issues persistently, kindly share them with me. Your cooperation is greatly appreciated.

![Screenshot from 2024-03-02 02-35-31](https://github.com/Adityaakr/Pay-Ease/assets/128833380/2755fac0-970e-4ea0-9b1c-e2e09959d80f)
